import _ from 'lodash';

// Helper functions
const slugify = s => _.kebabCase(s);
const addSlugsToSites = sites => {
    sites.forEach(site => {
        site.main_category_slug = slugify(site.main_category);
        site.site_name_slug = slugify(site.site_name);
    });
};
const groupBySlugs = sites => {
    let categories = {};
    for (let idx in sites) {
        let cat = sites[idx].main_category_slug; // slugified category
        let name = sites[idx].site_name_slug;
        if (!categories[cat]) categories[cat] = {};
        categories[cat][name] = sites[idx];
    }
    return categories;
};

// Data
let sitesMaster = [
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remote Ok',
        site_url: 'https://remoteok.io/',
        iframe_able: true,
        tags: ['remote', 'development', 'coding'],
        searchable: true,
        search_query_examples: [
            'https://remoteok.io/remote-video-editing-jobs',
            'https://remoteok.io/remote-customer-support+css-jobs',
        ],
        search_url: 'https://remoteok.io/remote-%q-jobs',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'CodePen Jobs',
        site_url: 'https://codepen.io/jobs/',
        iframe_able: true,
        tags: ['software', 'remote'],
        searchable: false,
        search_query_examples: ['https://codepen.io/jobs.json'],
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'GitHub Jobs',
        site_url: 'https://jobs.github.com/positions/',
        iframe_able: false,
        tags: ['software', 'remote'],
        searchable: true,
        search_query_examples: [
            'https://jobs.github.com/positions?utf8=%E2%9C%93&description=React&location=',
            'https://jobs.github.com/positions?utf8=%E2%9C%93&description=Java&location=San+Fransisco',
        ],
        search_url:
            'https://jobs.github.com/positions?utf8=%E2%9C%93&description=%q&location=',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'Monday.vc',
        site_url: 'https://www.monday.vc/jobs/',
        iframe_able: true,
        tags: ['software', 'remote', 'startups', 'venture backed'],
        searchable: true,
        search_query_examples: [
            'https://www.monday.vc/jobs?q=Dev%20Ops',
            'https://www.monday.vc/jobs?q=Content%20Creator',
        ],
        search_url: 'https://www.monday.vc/jobs?q=%q',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'TechStars',
        site_url: 'https://jobs.techstars.com/',
        iframe_able: true,
        tags: ['software', 'remote', 'startups', 'venture backed'],
        searchable: true,
        search_query_examples: [
            'https://jobs.techstars.com/?q=Intern',
            'https://jobs.techstars.com/?t=1197&j=1064993781&l=90',
        ],
        search_url: 'https://jobs.techstars.com/?q=%q',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'YC Engineering Jobs',
        site_url: 'https://www.workatastartup.com/',
        iframe_able: false,
        tags: [
            'software',
            'remote',
            'startups',
            'venture backed',
            'yc',
            'y combinator',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'YC Non-Engineering Jobs',
        site_url: 'https://ycombinator.monday.vc/',
        iframe_able: false,
        tags: ['remote', 'startups', 'venture backed', 'yc', 'y combinator'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Career Builder',
        site_url: 'https://www.careerbuilder.com/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [
            'https://www.careerbuilder.com/jobs?utf8=%E2%9C%93&keywords=Marketing&location=Austin+Tx',
            'https://www.careerbuilder.com/jobs?utf8=%E2%9C%93&keywords=React&location=Denver%2C+CO',
        ],
        search_url:
            'https://www.careerbuilder.com/jobs?utf8=%E2%9C%93&keywords=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Indeed',
        site_url: 'https://www.indeed.com/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [
            'https://www.indeed.com/q-full-stack-developer-l-College-Station,-TX-jobs.html',
            'https://www.indeed.com/jobs?q=theater+teacher&l=Oregon',
        ],
        search_url: 'https://www.indeed.com/jobs?q=%q',
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Twitch',
        site_url: 'https://boards.greenhouse.io/twitch',
        iframe_able: true,
        tags: ['tech', 'startups', 'gaming', 'video', 'software'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Glassdoor',
        site_url: 'https://www.glassdoor.com/index.htm/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [
            'https://www.glassdoor.com/Job/react-native-jobs-SRCH_KO0,12.htm',
            'https://www.glassdoor.com/Job/seattle-full-stack-web-dev-jobs-SRCH_IL.0,7_IC1150505_KE8,26.htm',
        ],
        search_url:
            'https://www.glassdoor.com/Job/jobs.htm?suggestCount=0&suggestChosen=false&clickSource=searchBtn&typedKeyword=%q&sc.keyword=%q&locT=&locId=&jobType=',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Google Jobs',
        site_url: 'https://www.google.com/search?q=jobs&ibp=htl;jobs',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_url: 'https://www.google.com/search?q=%q&ibp=htl;jobs',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'FlexJobs',
        site_url: 'https://www.flexjobs.com/jobs/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [
            'https://www.flexjobs.com/jobs/graphic-design',
            'https://www.flexjobs.com/search?search=Full+Stack+Web+Developer&location=Denver%2C+CO',
        ],
        search_url: 'https://www.flexjobs.com/search?search=%q',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'We Work Remotely',
        site_url: 'https://weworkremotely.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [
            'https://weworkremotely.com/remote-jobs/search?utf8=%E2%9C%93&term=React',
            'https://weworkremotely.com/remote-jobs/search?utf8=%E2%9C%93&term=React+Native',
        ],
        search_url:
            'https://weworkremotely.com/remote-jobs/search?utf8=%E2%9C%93&term=%q',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remote.co',
        site_url: 'https://remote.co/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [
            'https://remote.co/remote-jobs/search/?search_keywords=customer+service',
            'https://remote.co/remote-jobs/search/?search_keywords=Tech+Sales',
        ],
        search_url: 'https://remote.co/remote-jobs/search/?search_keywords=%q',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Virtual Vocation',
        site_url: 'https://www.virtualvocations.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [''],
        search_url: '',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Pangian',
        site_url: 'https://pangian.com/job-travel-remote/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remotive',
        site_url: 'https://remotive.io/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Working Nomads',
        site_url: 'https://www.workingnomads.co/jobs',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Jobspresso',
        site_url: 'https://jobspresso.co/remote-work/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Eurpoe Remote',
        site_url: 'https://europeremotely.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Outsourcely',
        site_url: 'https://www.outsourcely.com/remote-workers',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Power To Fly',
        site_url: 'https://powertofly.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'women'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Landing Jobs',
        site_url: 'https://landing.jobs/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://landing.jobs/jobs?page=1&q=%q&hd=false&t_co=false&t_st=false',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Authentic Jobs',
        site_url: 'https://authenticjobs.com/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://authenticjobs.com/#query=%q',
    },
    {
        main_category: 'Design',
        type: 'job-board',
        site_name: 'Dribbble',
        site_url: 'https://dribbble.com/jobs',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: '99designs',
        site_url: 'https://99designs.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'job-board',
        site_name: 'Behance',
        site_url: 'https://www.behance.net/joblist',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: 'DesignCrowd',
        site_url: 'https://jobs.designcrowd.com/jobs/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: 'Envato Studio',
        site_url: 'https://studio.envato.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: 'Working Not Working',
        site_url: 'https://workingnotworking.com/search/jobs/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: true,
        search_query_examples: [
            'https://workingnotworking.com/search/everywhere/jobs/ux-ia-designer',
            'https://workingnotworking.com/search/new-york-ny-usa',
        ],
        search_url: 'https://workingnotworking.com/search/everywhere/jobs/%q',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'Stack Overflow',
        site_url: 'https://stackoverflow.com/jobs/',
        iframe_able: false,
        tags: [
            'software',
            'part-time',
            'freelance',
            'software engineering',
            'remote',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://stackoverflow.com/search?q=%q',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'Smashing Jobs',
        site_url: 'https://jobs.smashingmagazine.com/jobs/',
        iframe_able: false,
        tags: [
            'software',
            'part-time',
            'freelance',
            'design',
            'remote',
            'developers',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'The Muse',
        site_url: 'https://www.themuse.com/jobs/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.themuse.com/search/jobs?keyword=%q&filter=true',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Idealist',
        site_url: 'https://www.idealist.org/en/?searchMode=true&type=JOB/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate', 'internships', 'startups'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.idealist.org/en/?q=%q&searchMode=true&sort=relevance&type=JOB',
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Cryptocurrency Jobs',
        site_url: 'https://cryptocurrencyjobs.co/',
        iframe_able: true,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://cryptocurrencyjobs.co/?query=%q',
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'CryptoJobs',
        site_url: 'https://crypto.jobs',
        iframe_able: false,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Crypto Jobs List',
        site_url: 'https://cryptojobslist.com/',
        iframe_able: true,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://cryptojobslist.com/blockchain-%q-jobs',
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Crypto Careers',
        site_url: 'https://www.crypto-careers.com/',
        iframe_able: false,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.crypto-careers.com/jobs/search?utf8=%E2%9C%93&q=%q&cat=&l=&lat=&long=&d=',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'F6S',
        site_url: 'https://www.f6s.com/jobs?sort=newest/',
        iframe_able: false,
        tags: ['software', 'startups', 'operations', ''],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.f6s.com/jobs?keywords[]=%q&sort=newest',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'Growth Hackers',
        site_url: 'https://growthhackers.com/jobs/',
        iframe_able: false,
        tags: ['software', 'startups', 'operations', 'growth hacker', 'growth'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Software',
        type: 'match-service',
        site_name: 'Gun.io',
        site_url: 'https://www.gun.io/',
        iframe_able: true,
        tags: ['software'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'US.jobs',
        site_url: 'https://us.jobs/search/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'temporary', 'minority'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://us.jobs/search?keyword=%q',
    },
    {
        main_category: 'Software',
        type: 'company',
        site_name: 'GitLab',
        site_url: 'https://boards.greenhouse.io/gitlab',
        iframe_able: true,
        tags: ['software'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Software',
        type: 'company',
        site_name: 'WP Hired',
        site_url: 'https://www.wphired.com/jobs/',
        iframe_able: false,
        tags: ['software', 'sales', 'customer service'],
        searchable: true,
        search_query_examples: [
            'https://www.wphired.com/jobs/?search_keywords=sales&search_region=0&search_categories%5B%5D=&submit=Search&filter_job_type%5B%5D=',
        ],
        search_url: 'https://www.wphired.com/jobs/?search_keywords=%q',
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Airbnb',
        site_url: 'https://careers.airbnb.com/',
        iframe_able: false,
        tags: ['photography', 'sales', 'customer service', 'software'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Amazon',
        site_url: 'https://www.amazon.jobs/',
        iframe_able: false,
        tags: ['university', 'sales', 'customer service', 'software', 'entry'],
        searchable: true,
        search_query_examples: [
            'https://www.amazon.jobs/en-gb/search?base_query=Utah&loc_query=',
        ],
        search_url: '',
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Microsoft',
        site_url: 'https://careers.microsoft.com/',
        iframe_able: false,
        tags: ['university', 'sales', 'customer service', 'software', 'entry'],
        searchable: true,
        search_query_examples: [
            'https://careers.microsoft.com/us/en/search-results?keywords=Sales',
        ],
        search_url: 'https://www.amazon.jobs/en-gb/search?base_query=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Salesforce Job Board',
        site_url: 'https://appexchange.salesforce.com/jobs',
        iframe_able: true,
        tags: ['software', 'sales', 'customer service'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Health Care',
        type: 'job-board',
        site_name: 'Health Ecareers',
        site_url: 'https://www.healthecareers.com/search-jobs/',
        iframe_able: true,
        tags: ['health care', 'medical', 'nurse', 'internship', 'doctors'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Health Care',
        type: 'job-board',
        site_name: 'Career Vitals',
        site_url: 'http://www.careervitals.com/',
        iframe_able: true,
        tags: ['health care', 'medical', 'nurse', 'internship', 'doctors'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.careervitals.com/search.php?strKeyword=%q',
    },
    {
        main_category: 'Health Care',
        type: 'job-board',
        site_name: 'MD Jobsite',
        site_url: 'https://www.mdjobsite.com/',
        iframe_able: true,
        tags: ['health care', 'medical', 'nurse', 'internship', 'doctors'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Health Care',
        type: 'job-board',
        site_name: 'MedZilla',
        site_url: 'http://www.medzilla.com',
        iframe_able: true,
        tags: [
            'health care',
            'medical',
            'pharmaceutical',
            'biotech',
            'science',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Health Care',
        type: 'job-board',
        site_name: 'Healthcare Jobsite',
        site_url: 'https://www.healthcarejobsite.com',
        iframe_able: true,
        tags: [
            'health care',
            'medical',
            'pharmaceutical',
            'nursing',
            'science',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.healthcarejobsite.com/jobs/search?k=%q',
    },
    {
        main_category: 'Health Care',
        type: 'job-board',
        site_name: 'Nursing Jobs',
        site_url: 'https://www.nursingjobs.com/',
        iframe_able: true,
        tags: ['health care', 'medical', 'nursing', 'science'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.nursingjobs.com/jobs/k-%q-l-/?clear=true',
    },
    {
        main_category: 'Health Care',
        type: 'job-board',
        site_name: 'Gas Work',
        site_url: 'https://www.gaswork.com/',
        iframe_able: true,
        tags: ['medical gas', 'medical', 'gas'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Monster.com',
        site_url: 'https://monster.com/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.monster.com/jobs/search/?q=%q&intcid=skr_navigation_nhpso_searchMain',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Simply Hired',
        site_url: 'https://www.simplyhired.com/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.simplyhired.com/search?q=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Zip Recruiter',
        site_url: 'https://ziprecruiter.com/Jobs/Search/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.ziprecruiter.com/candidate/search?search=%q',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Uber',
        site_url: 'https://www.uber.com/drive',
        iframe_able: false,
        tags: ['gig', 'driving', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Lyft',
        site_url: 'https://www.lyft.com/drive-with-lyft',
        iframe_able: true,
        tags: ['gig', 'driving', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Uber Eats',
        site_url: 'https://www.uber.com/drive/delivery/',
        iframe_able: false,
        tags: ['gig', 'driving', 'food delivery', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Grubhub',
        site_url: 'https://driver.grubhub.com/',
        iframe_able: true,
        tags: ['gig', 'driving', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'DoorDash',
        site_url: 'https://www.doordash.com/dasher/signup/',
        iframe_able: false,
        tags: ['gig', 'driving', 'food delivery', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'PostMates',
        site_url: 'https://fleet.postmates.com/',
        iframe_able: true,
        tags: ['gig', 'driving', 'food delivery', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'SimplePuppy',
        site_url: 'https://simplepuppy.com/',
        iframe_able: true,
        tags: ['gig', 'pets', 'pet sitting', 'part-time', 'pet grooming'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Wag!',
        site_url: 'https://wagwalking.com/dog-walker',
        iframe_able: false,
        tags: ['gig', 'pets', 'pet sitting', 'part-time', 'pet grooming'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Journalism Jobs',
        site_url: 'https://www.journalismjobs.com/job-listings',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Contena',
        site_url: 'https://www.contena.co/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'FWJ',
        site_url:
            'https://www.freelancewritinggigs.com/freelance-writing-job-ads/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Freelance Writing',
        site_url: 'https://www.freelancewriting.com/jobs/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'All Freelance Writing',
        site_url: 'https://allfreelancewriting.com/freelance-writing-jobs/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Media Bistro',
        site_url: 'https://www.mediabistro.com/jobs/openings/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'company',
        site_name: 'Due.com',
        site_url: 'https://due.com/guest-post-on-due/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'PubLoft',
        site_url: 'https://publoft.com/writers',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board, request driven really',
        site_name: 'Contently',
        site_url: 'https://contently.net/about-us/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Production Hub',
        site_url: 'https://www.productionhub.com/jobs',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Stage 32',
        site_url: 'https://www.stage32.com/find-jobs',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Assemble',
        site_url: 'https://www.assemble.tv/talent',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Mandy',
        site_url: 'https://www.mandy.com/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
            'theatre',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'LinkedIn Jobs',
        site_url: 'https://www.linkedin.com/jobs/search/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
            'theatre',
        ],
        searchable: true,
        search_query_examples: [
            'https://www.linkedin.com/jobs/search?keywords=Front%20End%20Engineer&location=United%20States&trk=homepage-jobseeker_recent-search&redirect=false&position=1&pageNum=0',
            'https://www.linkedin.com/jobs/search?keywords=Video%20Editing&location=Denver%2C%20Colorado%2C%20United%20States&trk=guest_job_search_jobs-search-bar_search-submit&redirect=false&position=1&pageNum=0',
        ],
        search_url:
            'https://www.linkedin.com/jobs/search/?keywords=%q&location=United%20States',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Tech Ladies',
        site_url: 'https://www.hiretechladies.com/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
            'theatre',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: '',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Women For Hire',
        site_url: 'http://jobs.womenforhire.com/jobs/',
        iframe_able: false,
        tags: ['home', 'software', 'tech', 'women', 'female'],
        searchable: true,
        search_query_examples: [],
        search_url: '',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: "Women's Job List",
        site_url: 'https://www.womensjoblist.com',
        iframe_able: true,
        tags: ['home', 'tech', 'women', 'female'],
        searchable: true,
        search_query_examples: [],
        search_url: '',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Fairy God Boss',
        site_url: 'https://fairygodboss.com/jobs/filter',
        iframe_able: true,
        tags: ['home', 'tech', 'women', 'female'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://fairygodboss.com/search?term=%q',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Career Contessa',
        site_url: 'https://www.careercontessa.com/jobs/',
        iframe_able: true,
        tags: ['home', 'tech', 'women', 'female'],
        searchable: false,
        search_query_examples: [],
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'Campus Pride',
        site_url: 'https://campuspride.jobs/',
        iframe_able: true,
        tags: ['campus', 'pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: true,
        search_query_examples: ['https://campuspride.jobs/jobs/?q=nurse'],
        search_url: 'https://campuspride.jobs/jobs/?q=%q',
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'LGBT Centers',
        site_url: 'https://www.lgbtcenters.org/Careers',
        iframe_able: true,
        tags: ['pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: false,
        search_query_examples: [],
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'Pink Jobs',
        site_url: 'https://pink-jobs.com/jobs/',
        iframe_able: true,
        tags: ['pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: false,
        search_query_examples: [],
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'All LGBT Jobs',
        site_url: 'https://alllgbtjobs.com/',
        iframe_able: true,
        tags: ['pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://alllgbtjobs.com/s/find-%q-jobs-in-usa',
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'T Job Bank',
        site_url: 'http://tjobbank.com/',
        iframe_able: true,
        tags: ['pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: false,
        search_query_examples: [],
    },
    {
        main_category: 'Veterans',
        type: 'job-board',
        site_name: 'Veteran Jobs',
        site_url: 'http://vetjobs.com/',
        iframe_able: true,
        tags: ['military', 'veteran', 'army', 'navy', 'airforce', 'marines'],
        searchable: false,
        search_query_examples: [],
    },
    {
        main_category: 'Veterans',
        type: 'job-board',
        site_name: 'Recruit Military',
        site_url: 'https://recruitmilitary.com/job-seekers',
        iframe_able: true,
        tags: ['military', 'veteran', 'army', 'navy', 'airforce', 'marines'],
        searchable: true,
        search_query_examples: [
            'https://success.recruitmilitary.com/jobs?utf8=%E2%9C%93&keywords=army&location=&commit=Search',
        ],
        search_url:
            'https://success.recruitmilitary.com/jobs?keywords=%q&location=',
    },
    {
        main_category: 'Veterans',
        type: 'job-board',
        site_name: 'Hire Heroes USA',
        site_url: 'https://jobs.hireheroesusa.org',
        iframe_able: false,
        tags: ['military', 'veteran', 'army', 'navy', 'airforce', 'marines'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://jobs.hireheroesusa.org/jobs/search?utf8=%E2%9C%93&q=%q&l=&lat=&long=&d=',
    },
    {
        main_category: 'Veterans',
        type: 'job-board',
        site_name: 'Military.com',
        site_url: 'https://www.military.com/veteran-jobs',
        iframe_able: false,
        tags: ['military', 'veteran', 'army', 'navy', 'airforce', 'marines'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://www.military.com/jobsearch/jobs?q=%q&date-posted=-1&page_index=1&onprem=1',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Black Jobs',
        site_url: 'https://www.blackjobs.com/?/cgi-bin/jobs/postJob.cgi',
        iframe_able: false,
        tags: [
            'african american',
            'black',
            'minority',
            'african',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [
            'https://www.blackjobs.com/jobs/search?utf8=%E2%9C%93&q=act&l=College+Station%2C+TX&lat=30.6032&long=-96.3136&d=',
        ],
        search_url:
            'https://www.blackjobs.com/jobs/search?utf8=%E2%9C%93&q=%q&l=&lat=&long=&d=',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Black Career Network',
        site_url: 'https://www.blackcareernetwork.com/',
        iframe_able: true,
        tags: [
            'african american',
            'black',
            'minority',
            'african',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [
            'https://www.blackcareernetwork.com/job-summaries?keywords=actions&location=Washington%2C+DC&organization=',
        ],
        search_url:
            'https://www.blackcareernetwork.com/job-summaries?keywords=%q',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'IM Diversity',
        site_url: 'https://jobs.imdiversity.com/cm/candidate/search_jobs',
        iframe_able: false,
        tags: [
            'african american',
            'black',
            'minority',
            'hispanic',
            'asian',
            'african',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [
            'https://jobs.imdiversity.com/candidate/job_search/quick/results?sort_field=post_date&keyword=action&sort_dir=desc',
        ],
        search_url:
            'https://jobs.imdiversity.com/candidate/job_search/quick/results?sort_field=post_date&keyword=%q&sort_dir=desc',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Hispanic Today',
        site_url: 'https://hispanic-today.com/career-search-engine/',
        iframe_able: true,
        tags: ['minority', 'hispanic', 'spanish', 'people of color', 'poc'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://hispanic-today.com/career-search-engine/',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'HLPA',
        site_url: 'https://jobs.hlpa.com/jobs/',
        iframe_able: true,
        tags: ['minority', 'hispanic', 'spanish', 'people of color', 'poc'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://jobs.hlpa.com/jobs/?listing_type%5Bequal%5D=Job&searchId=1567052602.9847&action=search&keywords%5Ball_words%5D=%q',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Diversity Jobs',
        site_url: 'https://diversityjobs.com/',
        iframe_able: true,
        tags: [
            'minority',
            'pride',
            'black',
            'african',
            'hispanic',
            'spanish',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [
            'https://diversityjobs.com/js/find-action-jobs-in-usa/age:356',
        ],
        search_url: 'https://diversityjobs.com/js/find-%q-jobs-in-usa',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Diversity',
        site_url: 'https://www.diversity.com/list-jobs',
        iframe_able: true,
        tags: [
            'minority',
            'pride',
            'black',
            'african',
            'hispanic',
            'spanish',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.diversity.com/list-jobs',
    },
    {
        main_category: 'Justice Involved',
        type: 'job-board',
        site_name: '70 Million Jobs',
        site_url: 'https://www.70millionjobs.com/',
        iframe_able: true,
        tags: [
            'criminal',
            'felony',
            'felon',
            'misdemeanor',
            'crime',
            'convict',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.70millionjobs.com/search',
    },
    {
        main_category: 'Justice Involved',
        type: 'job-board',
        site_name: 'Jail To Job',
        site_url: 'https://www.jailtojob.com/companies-hire-felons.html',
        iframe_able: true,
        tags: [
            'criminal',
            'felony',
            'felon',
            'misdemeanor',
            'crime',
            'convict',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.jailtojob.com/companies-hire-felons.html',
    },
    {
        main_category: 'Justice Involved',
        type: 'job-board',
        site_name: 'Hire Felons',
        site_url: 'https://www.hirefelons.org/best-jobs-for-felons/',
        iframe_able: true,
        tags: [
            'criminal',
            'felony',
            'felon',
            'misdemeanor',
            'crime',
            'convict',
        ],
        searchable: false,
        search_query_examples: [],
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Recruit Disability',
        site_url: 'http://jobs.recruitdisability.org/jobs/search',
        iframe_able: true,
        tags: ['disabled', 'disability', 'impaired'],
        searchable: true,
        search_query_examples: [
            'http://jobs.recruitdisability.org/jobs/results/keyword/hearing/College+Station%2C+Texas?radius=25&SearchNetworks=US&networkView=national',
        ],
        search_url:
            'http://jobs.recruitdisability.org/jobs/results/title/%q?radius=25',
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Ability Links',
        site_url: 'https://abilitylinks.org/search/job',
        iframe_able: false,
        tags: ['disabled', 'disability', 'impaired'],
        searchable: true,
        search_query_examples: [
            'https://abilitylinks.org/search/job?search=distribution&field_job_region=All',
        ],
        search_url:
            'https://abilitylinks.org/search/job?search=%q&field_job_region=All',
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Getting Hired',
        site_url: 'https://www.gettinghired.com/',
        iframe_able: true,
        tags: ['disabled', 'disability', 'impaired', 'military'],
        searchable: true,
        search_query_examples: [
            'https://abilitylinks.org/search/job?search=distribution&field_job_region=All',
        ],
        search_url: 'https://www.gettinghired.com/?keyword=%q',
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Disability Job Exchange',
        site_url: 'https://www.disabilityjobexchange.com',
        iframe_able: true,
        tags: ['disabled', 'disability', 'impaired', 'military'],
        searchable: true,
        search_query_examples: [
            'https://abilitylinks.org/search/job?search=distribution&field_job_region=All',
        ],
        search_url: 'https://www.disabilityjobexchange.com/jobs/k-%q',
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Disabled Person',
        site_url: 'https://www.disabledperson.com',
        iframe_able: false,
        tags: ['disabled', 'disability', 'impaired', 'military'],
        searchable: true,
        search_query_examples: [
            'https://abilitylinks.org/search/job?search=distribution&field_job_region=All',
        ],
        search_url:
            'https://www.disabledperson.com/jobs?utf8=%E2%9C%93&term=%q&location=',
    },
];

// Processing
addSlugsToSites(sitesMaster); // run this in-place to save memory

// Exports
export const sites = sitesMaster;
export const sitesBySlug = groupBySlugs(sites);
