import _ from 'lodash';

// Helper functions
const slugify = s => _.kebabCase(s);
const addSlugsToSites = sites => {
    sites.forEach(site => {
        site.main_category_slug = slugify(site.main_category);
        site.site_name_slug = slugify(site.site_name);
    });
};
const groupBySlugs = sites => {
    let categories = {};
    for (let idx in sites) {
        let cat = sites[idx].main_category_slug; // slugified category
        let name = sites[idx].site_name_slug;
        if (!categories[cat]) categories[cat] = {};
        categories[cat][name] = sites[idx];
    }
    return categories;
};

// Data
let sitesMaster = [
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remote Ok',
        site_url: 'https://remoteok.io/',
        iframe_able: true,
        tags: ['remote', 'development', 'coding'],
        searchable: true,
        search_query_examples: [
            'https://remoteok.io/remote-video-editing-jobs',
            'https://remoteok.io/remote-customer-support+css-jobs',
        ],
        search_url: 'https://remoteok.io/remote-%q-jobs',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Workew',
        site_url: 'https://workew.com',
        iframe_able: true,
        tags: ['remote', 'development', 'coding'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://workew.com',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remotey',
        site_url: 'https://www.remotey.com/search/vacancy',
        iframe_able: false,
        tags: ['remote', 'development', 'coding'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.remotey.com/search/vacancy',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: '6 Nomads',
        site_url: 'https://6nomads.com/',
        iframe_able: false,
        tags: ['remote', 'development', 'coding', 'tech'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://6nomads.com/',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Wellpaid.io',
        site_url: 'https://wellpaid.io/',
        iframe_able: true,
        tags: ['remote', 'development', 'coding', 'tech'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://wellpaid.io/?q=%q',
    },
    {
        main_category: 'Product Manager',
        type: 'job-board',
        site_name: 'Product Hired',
        site_url: 'https://producthired.com/',
        iframe_able: true,
        tags: ['remote', 'product', 'product manager', 'PM', 'coding', 'tech'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://producthired.com/find-a-job/?search_keywords=%q',
    },
    {
        main_category: 'Product Manager',
        type: 'job-board',
        site_name: 'Work in Product',
        site_url: 'https://workinproduct.co/',
        iframe_able: true,
        tags: ['remote', 'product', 'product manager', 'PM', 'coding', 'tech'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://workinproduct.co/',
    },
    {
        main_category: 'Product Manager',
        type: 'job-board',
        site_name: 'Product School',
        site_url: 'https://www.productschool.com/job-portal/',
        iframe_able: true,
        tags: ['remote', 'product', 'product manager', 'PM', 'coding', 'tech'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.productschool.com/job-portal/',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'CodePen Jobs',
        site_url: 'https://codepen.io/jobs/',
        iframe_able: true,
        tags: ['software', 'remote'],
        searchable: false,
        search_query_examples: ['https://codepen.io/jobs.json'],
        search_url: 'https://codepen.io/jobs/',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'React JS Jobs',
        site_url: 'https://www.reactjobboard.com',
        iframe_able: true,
        tags: ['software', 'remote', 'react', 'react.js'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.reactjobboard.com/?query=%q',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'DevSnap',
        site_url: 'https://devsnap.io',
        iframe_able: true,
        tags: ['software', 'remote', 'developers', 'development'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://devsnap.io/jobs?s=%q',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'Epic Jobs',
        site_url: 'https://epicjobs.co',
        iframe_able: false,
        tags: ['software', 'remote', 'twitter', 'design', 'career'],
        searchable: false,
        search_query_examples: ['https://codepen.io/jobs.json'],
        search_url: 'https://epicjobs.co',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'Full Stack Jobs',
        site_url: 'https://fullstackjob.com',
        iframe_able: true,
        tags: ['software', 'full stack', 'web dev', 'web developer'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://fullstackjob.com',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'Golang Cafe',
        site_url: 'https://golang.cafe',
        iframe_able: false,
        tags: ['software', 'go', 'golang', 'go lang', 'google'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://golang.cafe/Golang-%q-Jobs',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'GitHub Jobs',
        site_url: 'https://jobs.github.com/positions/',
        iframe_able: false,
        tags: ['software', 'remote'],
        searchable: true,
        search_query_examples: [
            'https://jobs.github.com/positions?utf8=%E2%9C%93&description=React&location=',
            'https://jobs.github.com/positions?utf8=%E2%9C%93&description=Java&location=San+Fransisco',
        ],
        search_url:
            'https://jobs.github.com/positions?utf8=%E2%9C%93&description=%q&location=',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'Monday.vc',
        site_url: 'https://www.monday.vc/jobs/',
        iframe_able: true,
        tags: ['software', 'remote', 'startups', 'venture backed'],
        searchable: true,
        search_query_examples: [
            'https://www.monday.vc/jobs?q=Dev%20Ops',
            'https://www.monday.vc/jobs?q=Content%20Creator',
        ],
        search_url: 'https://www.monday.vc/jobs?q=%q',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'Angel.co',
        site_url: 'https://angel.co/',
        iframe_able: false,
        tags: ['software', 'remote', 'startups', 'venture backed'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://angel.co/',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'TechStars',
        site_url: 'https://jobs.techstars.com/',
        iframe_able: true,
        tags: ['software', 'remote', 'startups', 'venture backed'],
        searchable: true,
        search_query_examples: [
            'https://jobs.techstars.com/?q=Intern',
            'https://jobs.techstars.com/?t=1197&j=1064993781&l=90',
        ],
        search_url: 'https://jobs.techstars.com/?q=%q',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'YC Engineering Jobs',
        site_url: 'https://www.workatastartup.com/',
        iframe_able: false,
        tags: [
            'software',
            'remote',
            'startups',
            'venture backed',
            'yc',
            'y combinator',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.workatastartup.com/',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'YC Non-Engineering Jobs',
        site_url: 'https://ycombinator.monday.vc/',
        iframe_able: false,
        tags: ['remote', 'startups', 'venture backed', 'yc', 'y combinator'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://ycombinator.monday.vc/',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'Product Hunt Jobs',
        site_url: 'https://www.producthunt.com/jobs',
        iframe_able: false,
        tags: ['remote', 'startups', 'venture backed', 'products'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.producthunt.com/jobs',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'Startup Jobs',
        site_url: 'https://startup.jobs/',
        iframe_able: false,
        tags: ['remote', 'startups', 'start up', 'venture backed', 'products'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://startup.jobs/?q=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Career Builder',
        site_url: 'https://www.careerbuilder.com/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [
            'https://www.careerbuilder.com/jobs?utf8=%E2%9C%93&keywords=Marketing&location=Austin+Tx',
            'https://www.careerbuilder.com/jobs?utf8=%E2%9C%93&keywords=React&location=Denver%2C+CO',
        ],
        search_url:
            'https://www.careerbuilder.com/jobs?utf8=%E2%9C%93&keywords=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Jobbydoo',
        site_url: 'https://www.jobbydoo.com/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.jobbydoo.com/?j=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Indeed',
        site_url: 'https://www.indeed.com/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [
            'https://www.indeed.com/q-full-stack-developer-l-College-Station,-TX-jobs.html',
            'https://www.indeed.com/jobs?q=theater+teacher&l=Oregon',
        ],
        search_url: 'https://www.indeed.com/jobs?q=%q',
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Twitch',
        site_url: 'https://boards.greenhouse.io/twitch',
        iframe_able: true,
        tags: ['tech', 'startups', 'gaming', 'video', 'software'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://boards.greenhouse.io/twitch',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Glassdoor',
        site_url: 'https://www.glassdoor.com/index.htm/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [
            'https://www.glassdoor.com/Job/react-native-jobs-SRCH_KO0,12.htm',
            'https://www.glassdoor.com/Job/seattle-full-stack-web-dev-jobs-SRCH_IL.0,7_IC1150505_KE8,26.htm',
        ],
        search_url:
            'https://www.glassdoor.com/Job/jobs.htm?suggestCount=0&suggestChosen=false&clickSource=searchBtn&typedKeyword=%q&sc.keyword=%q&locT=&locId=&jobType=',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Google Jobs',
        site_url: 'https://www.google.com/search?q=jobs&ibp=htl;jobs',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_url: 'https://www.google.com/search?q=%q&ibp=htl;jobs',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Job Diagnosis',
        site_url: 'https://www.jobdiagnosis.com/search.php',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_url: 'https://search.jobdiagnosis.com/index.php?keyword=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Employment Alert',
        site_url: 'https://www.employmentalert.com/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_url: 'https://www.employmentalert.com/search.php?keyword=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'My Job Helper',
        site_url: 'https://www.myjobhelper.com/index',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_url: 'https://www.myjobhelper.com/search?q=%q&l=',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'My Job Helper',
        site_url: 'https://www.myjobhelper.com/index',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_url: 'https://www.myjobhelper.com/search?q=%q&l=',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Snag',
        site_url: 'https://www.snagajob.com/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_url: 'https://www.snagajob.com/search?q=%q',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'FlexJobs',
        site_url: 'https://www.flexjobs.com/jobs/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [
            'https://www.flexjobs.com/jobs/graphic-design',
            'https://www.flexjobs.com/search?search=Full+Stack+Web+Developer&location=Denver%2C+CO',
        ],
        search_url: 'https://www.flexjobs.com/search?search=%q',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'We Work Remotely',
        site_url: 'https://weworkremotely.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [
            'https://weworkremotely.com/remote-jobs/search?utf8=%E2%9C%93&term=React',
            'https://weworkremotely.com/remote-jobs/search?utf8=%E2%9C%93&term=React+Native',
        ],
        search_url:
            'https://weworkremotely.com/remote-jobs/search?utf8=%E2%9C%93&term=%q',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remote.co',
        site_url: 'https://remote.co/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [
            'https://remote.co/remote-jobs/search/?search_keywords=customer+service',
            'https://remote.co/remote-jobs/search/?search_keywords=Tech+Sales',
        ],
        search_url: 'https://remote.co/remote-jobs/search/?search_keywords=%q',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Virtual Vocation',
        site_url: 'https://www.virtualvocations.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.virtualvocations.com/',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Pangian',
        site_url: 'https://pangian.com/job-travel-remote/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://pangian.com/job-travel-remote/',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remotive',
        site_url: 'https://remotive.io/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://remotive.io/',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Working Nomads',
        site_url: 'https://www.workingnomads.co/jobs',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.workingnomads.co/jobs',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Jobspresso',
        site_url: 'https://jobspresso.co/remote-work/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://jobspresso.co/remote-work/',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Eurpoe Remote',
        site_url: 'https://europeremotely.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://europeremotely.com/',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Outsourcely',
        site_url: 'https://www.outsourcely.com/remote-workers',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.outsourcely.com/remote-workers',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Power To Fly',
        site_url: 'https://powertofly.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'women'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://powertofly.com/',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Landing Jobs',
        site_url: 'https://landing.jobs/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://landing.jobs/jobs?page=1&q=%q&hd=false&t_co=false&t_st=false',
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Authentic Jobs',
        site_url: 'https://authenticjobs.com/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://authenticjobs.com/#query=%q',
    },
    {
        main_category: 'Design',
        type: 'job-board',
        site_name: 'Dribbble',
        site_url: 'https://dribbble.com/jobs',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://dribbble.com/jobs',
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: '99designs',
        site_url: 'https://99designs.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://99designs.com/',
    },
    {
        main_category: 'Design',
        type: 'job-board',
        site_name: 'Behance',
        site_url: 'https://www.behance.net/joblist',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.behance.net/joblist',
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: 'DesignCrowd',
        site_url: 'https://jobs.designcrowd.com/jobs/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://jobs.designcrowd.com/jobs/',
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: 'Envato Studio',
        site_url: 'https://studio.envato.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://studio.envato.com/',
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: 'Working Not Working',
        site_url: 'https://workingnotworking.com/search/jobs/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: true,
        search_query_examples: [
            'https://workingnotworking.com/search/everywhere/jobs/ux-ia-designer',
            'https://workingnotworking.com/search/new-york-ny-usa',
        ],
        search_url: 'https://workingnotworking.com/search/everywhere/jobs/%q',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'Stack Overflow',
        site_url: 'https://stackoverflow.com/jobs/',
        iframe_able: false,
        tags: [
            'software',
            'part-time',
            'freelance',
            'software engineering',
            'remote',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://stackoverflow.com/search?q=%q',
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'Smashing Jobs',
        site_url: 'https://jobs.smashingmagazine.com/jobs/',
        iframe_able: false,
        tags: [
            'software',
            'part-time',
            'freelance',
            'design',
            'remote',
            'developers',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://jobs.smashingmagazine.com/jobs/',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'The Muse',
        site_url: 'https://www.themuse.com/jobs/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.themuse.com/search/jobs?keyword=%q&filter=true',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'JuJu',
        site_url: 'https://www.juju.com/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.juju.com/jobs?k=%q&l=&r=20',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'My Job Matcher',
        site_url: 'https://www.myjobmatcher.com/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.myjobmatcher.com/jobs?jr=%q&lc=&ds=&os=0',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Upward',
        site_url: 'https://www.upward.net/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.upward.careers/results.jsp?reg=0&job=%q&location=',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Jobg8',
        site_url: 'http://www.jobg8.com/Homepage.aspx',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'http://www.jobg8.com/Homepage.aspx',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Job Rapido',
        site_url: 'https://us.jobrapido.com/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://us.jobrapido.com/?w=%q&shm=all',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Job 2 Careers',
        site_url: 'https://www.jobs2careers.com/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.jobs2careers.com/results3.php?q=%q&l=',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Neuvoo',
        site_url: 'https://neuvoo.com/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://neuvoo.com/jobs/?k=%q&l=&f=&o=&p=&r=15',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Startwire',
        site_url: 'https://www.startwire.com/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.startwire.com/job/search?query=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Career Bliss',
        site_url: 'https://www.careerbliss.com/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.careerbliss.com/search/?q=%q&l=&typeFilter=job&sf=true',
    },
    {
        main_category: 'Executive',
        type: 'job-board',
        site_name: 'Lens',
        site_url: 'https://lens.careers/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://lens.careers/',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'Idealist',
        site_url: 'https://www.idealist.org/en/?searchMode=true&type=JOB/',
        iframe_able: false,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.idealist.org/en/?q=%q&searchMode=true&sort=relevance&type=JOB',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'GIIN',
        site_url: 'https://jobs.thegiin.org/',
        iframe_able: true,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://jobs.thegiin.org/career/search/?search=%q',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'B Corporation',
        site_url: 'https://bcorporation.net/directory/jobs-board',
        iframe_able: false,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://bcorporation.net/directory?search=%q',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'Bridgespan',
        site_url:
            'https://www.bridgespan.org/jobs/nonprofit-jobs/nonprofit-job-board',
        iframe_able: false,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.bridgespan.org/jobs/nonprofit-jobs/nonprofit-job-board',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'B Meaningful',
        site_url: 'https://www.bmeaningful.com/search',
        iframe_able: true,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.bmeaningful.com/search',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'tbd*',
        site_url: 'https://www.tbd.community/en/jobs',
        iframe_able: false,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.tbd.community/en/jobs?search=%q',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'Relief Web',
        site_url: 'https://reliefweb.int/jobs',
        iframe_able: true,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://reliefweb.int/jobs',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: '80,000 Hours',
        site_url: 'https://80000hours.org/job-board/',
        iframe_able: true,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://80000hours.org/job-board/',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'Tech Jobs For Good',
        site_url: 'https://www.techjobsforgood.com',
        iframe_able: false,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.techjobsforgood.com/?q=%q',
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Cryptocurrency Jobs',
        site_url: 'https://cryptocurrencyjobs.co/',
        iframe_able: true,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://cryptocurrencyjobs.co/?query=%q',
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Blockew',
        site_url: 'https://blockew.com',
        iframe_able: true,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://blockew.com/crypto-blockchain-jobs/',
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'CryptoJobs',
        site_url: 'https://crypto.jobs',
        iframe_able: false,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://crypto.jobs',
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Crypto Jobs List',
        site_url: 'https://cryptojobslist.com/',
        iframe_able: true,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://cryptojobslist.com/blockchain-%q-jobs',
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Crypto Careers',
        site_url: 'https://www.crypto-careers.com/',
        iframe_able: false,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.crypto-careers.com/jobs/search?utf8=%E2%9C%93&q=%q&cat=&l=&lat=&long=&d=',
    },
    {
        main_category: 'A.I.',
        type: 'job-board',
        site_name: 'A.I. Jobs',
        site_url: 'https://ai-jobs.net',
        iframe_able: true,
        tags: [
            'software',
            'startups',
            'AI',
            'a.i.',
            'artificial intelligence',
            'data',
            'data science',
            'analyst',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://ai-jobs.net',
    },
    {
        main_category: 'A.I.',
        type: 'job-board',
        site_name: 'I Crunch Data',
        site_url: 'https://icrunchdata.com/jobs/',
        iframe_able: true,
        tags: [
            'software',
            'startups',
            'AI',
            'a.i.',
            'artificial intelligence',
            'data',
            'data science',
            'analyst',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://icrunchdata.com/jobs/?q=%q',
    },
    {
        main_category: 'A.I.',
        type: 'job-board',
        site_name: 'A.I. Jobs Global',
        site_url: 'https://ai-jobs.global',
        iframe_able: true,
        tags: [
            'software',
            'startups',
            'AI',
            'a.i.',
            'artificial intelligence',
            'data',
            'data science',
            'analyst',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://ai-jobs.global/browse-jobs/?search_keywords=%q',
    },
    {
        main_category: 'A.I.',
        type: 'job-board',
        site_name: 'Stella',
        site_url: 'https://www.stella.ai/',
        iframe_able: false,
        tags: [
            'software',
            'startups',
            'AI',
            'a.i.',
            'artificial intelligence',
            'data',
            'data science',
            'analyst',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.stella.ai/',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'Entry Level Jobs',
        site_url: 'https://www.entryleveljobs.me',
        iframe_able: true,
        tags: [
            'software',
            'entry level',
            'entry',
            'starting',
            'post-grad',
            'post grad',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.entryleveljobs.me/?q=%q',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'Living Wage Interns',
        site_url: 'https://www.livingwageinterns.com/',
        iframe_able: true,
        tags: ['entry level', 'entry', 'starting', 'post-grad', 'post grad'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.livingwageinterns.com/',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'Remote Internships',
        site_url: 'http://remoteinternships.co',
        iframe_able: true,
        tags: [
            'software',
            'entry level',
            'entry',
            'starting',
            'post-grad',
            'post grad',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'http://remoteinternships.co',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'Way Up',
        site_url: 'https://www.wayup.com/',
        iframe_able: false,
        tags: ['university', 'internships', 'entry', 'summer', 'part-time'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.wayup.com/',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'Intern Jobs',
        site_url: 'https://www.internjobs.com/',
        iframe_able: false,
        tags: ['university', 'internships', 'entry', 'summer', 'part-time'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://www.internjobs.com/job/search?keyword=%q&location=&Action=Search',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'Chegg Internships',
        site_url: 'https://www.internships.com/',
        iframe_able: false,
        tags: ['university', 'internships', 'entry', 'summer', 'part-time'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://student.internships.com/search?keywords=%q&position-types=internship&location=&context=seo&seo-mcid=-1',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'College Recruiter',
        site_url: 'https://www.collegerecruiter.com/',
        iframe_able: false,
        tags: ['university', 'internships', 'entry', 'summer', 'part-time'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://www.collegerecruiter.com/job-search?keyword=%q&location=latitude=&longitude=',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'Handshake',
        site_url: 'https://joinhandshake.com/',
        iframe_able: true,
        tags: ['university', 'internships', 'entry', 'summer', 'part-time'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://joinhandshake.com/',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'Graduate Jobs',
        site_url: 'https://www.graduate-jobs.com/',
        iframe_able: false,
        tags: ['university', 'internships', 'entry', 'summer', 'part-time'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.graduate-jobs.com/search?q=%q',
    },
    {
        main_category: 'Entry Level',
        type: 'job-board',
        site_name: 'Her Campus',
        site_url: 'https://www.hercampus.com/job-board',
        iframe_able: false,
        tags: ['university', 'internships', 'entry', 'summer', 'part-time'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.hercampus.com/job-board',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'F6S',
        site_url: 'https://www.f6s.com/jobs?sort=newest/',
        iframe_able: false,
        tags: ['software', 'startups', 'operations', ''],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.f6s.com/jobs?keywords[]=%q&sort=newest',
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'Growth Hackers',
        site_url: 'https://growthhackers.com/jobs/',
        iframe_able: false,
        tags: ['software', 'startups', 'operations', 'growth hacker', 'growth'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://growthhackers.com/jobs/',
    },
    {
        main_category: 'Software',
        type: 'match-service',
        site_name: 'Gun.io',
        site_url: 'https://www.gun.io/',
        iframe_able: true,
        tags: ['software'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.gun.io/',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'US.jobs',
        site_url: 'https://us.jobs/search/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'temporary', 'minority'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://us.jobs/search?keyword=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Job.com',
        site_url: 'https://www.job.com/',
        iframe_able: true,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.job.com/',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Jobot',
        site_url: 'https://jobot.com/',
        iframe_able: true,
        tags: [
            'career',
            'all jobs',
            'corporate',
            'marketing',
            'healthcare',
            'construction',
            'automotive',
            'biotech',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://jobot.com/search/?q=%q&l=',
    },
    {
        main_category: 'Software',
        type: 'company',
        site_name: 'GitLab',
        site_url: 'https://boards.greenhouse.io/gitlab',
        iframe_able: true,
        tags: ['software'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://boards.greenhouse.io/gitlab',
    },
    {
        main_category: 'Software',
        type: 'company',
        site_name: 'WP Hired',
        site_url: 'https://www.wphired.com/jobs/',
        iframe_able: false,
        tags: ['software', 'sales', 'customer service'],
        searchable: true,
        search_query_examples: [
            'https://www.wphired.com/jobs/?search_keywords=sales&search_region=0&search_categories%5B%5D=&submit=Search&filter_job_type%5B%5D=',
        ],
        search_url: 'https://www.wphired.com/jobs/?search_keywords=%q',
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Airbnb',
        site_url: 'https://careers.airbnb.com/',
        iframe_able: false,
        tags: ['photography', 'sales', 'customer service', 'software'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://careers.airbnb.com/',
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Amazon',
        site_url: 'https://www.amazon.jobs/',
        iframe_able: false,
        tags: ['university', 'sales', 'customer service', 'software', 'entry'],
        searchable: true,
        search_query_examples: [
            'https://www.amazon.jobs/en-gb/search?base_query=Utah&loc_query=',
        ],
        search_url: 'https://www.amazon.jobs/',
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Microsoft',
        site_url: 'https://careers.microsoft.com/',
        iframe_able: false,
        tags: ['university', 'sales', 'customer service', 'software', 'entry'],
        searchable: true,
        search_query_examples: [
            'https://careers.microsoft.com/us/en/search-results?keywords=Sales',
        ],
        search_url:
            'https://careers.microsoft.com/us/en/search-results?keywords=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Salesforce Job Board',
        site_url: 'https://appexchange.salesforce.com/jobs',
        iframe_able: true,
        tags: ['software', 'sales', 'customer service'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://appexchange.salesforce.com/jobs',
    },
    {
        main_category: 'Healthcare',
        type: 'job-board',
        site_name: 'Health Ecareers',
        site_url: 'https://www.healthecareers.com/search-jobs/',
        iframe_able: true,
        tags: ['Healthcare', 'medical', 'nurse', 'internship', 'doctors'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.healthecareers.com/search-jobs/',
    },
    {
        main_category: 'Healthcare',
        type: 'job-board',
        site_name: 'Career Vitals',
        site_url: 'http://www.careervitals.com/',
        iframe_able: true,
        tags: ['Healthcare', 'medical', 'nurse', 'internship', 'doctors'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.careervitals.com/search.php?strKeyword=%q',
    },
    {
        main_category: 'Healthcare',
        type: 'job-board',
        site_name: 'MD Jobsite',
        site_url: 'https://www.mdjobsite.com/',
        iframe_able: true,
        tags: ['Healthcare', 'medical', 'nurse', 'internship', 'doctors'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.mdjobsite.com/',
    },
    {
        main_category: 'Healthcare',
        type: 'job-board',
        site_name: 'MedZilla',
        site_url: 'http://www.medzilla.com',
        iframe_able: true,
        tags: ['Healthcare', 'medical', 'pharmaceutical', 'biotech', 'science'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'http://www.medzilla.com',
    },
    {
        main_category: 'Healthcare',
        type: 'job-board',
        site_name: 'Healthcare Jobsite',
        site_url: 'https://www.healthcarejobsite.com',
        iframe_able: true,
        tags: ['Healthcare', 'medical', 'pharmaceutical', 'nursing', 'science'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.healthcarejobsite.com/jobs/search?k=%q',
    },
    {
        main_category: 'Healthcare',
        type: 'job-board',
        site_name: 'Nursing Jobs',
        site_url: 'https://www.nursingjobs.com/',
        iframe_able: true,
        tags: ['Healthcare', 'medical', 'nursing', 'science'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.nursingjobs.com/jobs/k-%q-l-/?clear=true',
    },
    {
        main_category: 'Healthcare',
        type: 'job-board',
        site_name: 'Gas Work',
        site_url: 'https://www.gaswork.com/',
        iframe_able: true,
        tags: ['medical gas', 'medical', 'gas'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.gaswork.com/',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Monster.com',
        site_url: 'https://monster.com/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.monster.com/jobs/search/?q=%q&intcid=skr_navigation_nhpso_searchMain',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Simply Hired',
        site_url: 'https://www.simplyhired.com/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.simplyhired.com/search?q=%q',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Zip Recruiter',
        site_url: 'https://ziprecruiter.com/Jobs/Search/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'corporate'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.ziprecruiter.com/candidate/search?search=%q',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Uber',
        site_url: 'https://www.uber.com/drive',
        iframe_able: false,
        tags: ['gig', 'driving', 'part-time'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.uber.com/drive',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Freelancer',
        site_url: 'https://www.freelancer.com/jobs',
        iframe_able: false,
        tags: ['gig', 'freelance', 'contract', 'remote'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.freelancer.com/jobs/?keyword=%q',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Upwork',
        site_url: 'https://www.upwork.com/search/jobs/?sort=relevance%2Bdesc',
        iframe_able: false,
        tags: ['gig', 'freelance', 'contract', 'remote'],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.upwork.com/search/jobs/?q=%q&sort=relevance%2Bdesc',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Fiverr',
        site_url: 'https://www.fiverr.com/',
        iframe_able: false,
        tags: ['gig', 'freelance', 'contract', 'remote'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.fiverr.com/search/gigs?query=%q',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Lyft',
        site_url: 'https://www.lyft.com/drive-with-lyft',
        iframe_able: true,
        tags: ['gig', 'driving', 'part-time'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.lyft.com/drive-with-lyft',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Uber Eats',
        site_url: 'https://www.uber.com/drive/delivery/',
        iframe_able: false,
        tags: ['gig', 'driving', 'food delivery', 'part-time'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.uber.com/drive/delivery/',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Grubhub',
        site_url: 'https://driver.grubhub.com/',
        iframe_able: true,
        tags: ['gig', 'driving', 'part-time'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://driver.grubhub.com/',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'DoorDash',
        site_url: 'https://www.doordash.com/dasher/signup/',
        iframe_able: false,
        tags: ['gig', 'driving', 'food delivery', 'part-time'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.doordash.com/dasher/signup/',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'PostMates',
        site_url: 'https://fleet.postmates.com/',
        iframe_able: true,
        tags: ['gig', 'driving', 'food delivery', 'part-time'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://fleet.postmates.com/',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'SimplePuppy',
        site_url: 'https://simplepuppy.com/',
        iframe_able: true,
        tags: ['gig', 'pets', 'pet sitting', 'part-time', 'pet grooming'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://simplepuppy.com/',
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Wag!',
        site_url: 'https://wagwalking.com/dog-walker',
        iframe_able: false,
        tags: ['gig', 'pets', 'pet sitting', 'part-time', 'pet grooming'],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://wagwalking.com/dog-walker',
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Journalism Jobs',
        site_url: 'https://www.journalismjobs.com/job-listings',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.journalismjobs.com/job-listings',
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Mediab',
        site_url: 'https://www.journalismjobs.com/job-listings',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.journalismjobs.com/job-listings',
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Contena',
        site_url: 'https://www.contena.co/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.contena.co/',
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'FWJ',
        site_url:
            'https://www.freelancewritinggigs.com/freelance-writing-job-ads/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url:
            'https://www.freelancewritinggigs.com/freelance-writing-job-ads/',
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Freelance Writing',
        site_url: 'https://www.freelancewriting.com/jobs/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.freelancewriting.com/jobs/',
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'All Freelance Writing',
        site_url: 'https://allfreelancewriting.com/freelance-writing-jobs/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://allfreelancewriting.com/freelance-writing-jobs/',
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Media Bistro',
        site_url: 'https://www.mediabistro.com/jobs/openings/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.mediabistro.com/jobs/openings/',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'Net Impact',
        site_url: 'https://www.netimpact.org/jobs',
        iframe_able: false,
        tags: ['social good', 'social impact', 'global good', 'welfare'],
        searchable: true,
        search_query_examples: [''],
        search_url: 'https://www.netimpact.org/jobs?jobkey=%q',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'Devex',
        site_url: 'https://www.devex.com/jobs',
        iframe_able: false,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: true,
        search_query_examples: [''],
        search_url:
            'https://www.devex.com/jobs/search?filter%5Bjob_titles%5D%5B%5D=%q&sorting%5Border%5D=desc&sorting%5Bfield%5D=_score',
    },
    {
        main_category: 'Social Good',
        type: 'job-board',
        site_name: 'Next Billion',
        site_url: 'https://nextbillion.net/jobs/',
        iframe_able: true,
        tags: [
            'social good',
            'development',
            'software',
            'social impact',
            'global good',
            'welfare',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://nextbillion.net/jobs/',
    },
    {
        main_category: 'Writing',
        type: 'company',
        site_name: 'Due.com',
        site_url: 'https://due.com/guest-post-on-due/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://due.com/guest-post-on-due/',
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'PubLoft',
        site_url: 'https://publoft.com/writers',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://publoft.com/writers',
    },
    {
        main_category: 'Writing',
        type: 'job-board, request driven really',
        site_name: 'Contently',
        site_url: 'https://contently.net/about-us/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://contently.net/about-us/',
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Production Hub',
        site_url: 'https://www.productionhub.com/jobs',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.productionhub.com/jobs',
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Stage 32',
        site_url: 'https://www.stage32.com/find-jobs',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.stage32.com/find-jobs',
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Assemble',
        site_url: 'https://www.assemble.tv/talent',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.assemble.tv/talent',
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Mandy',
        site_url: 'https://www.mandy.com/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
            'theatre',
        ],
        searchable: false,
        search_query_examples: [''],
        search_url: 'https://www.mandy.com/',
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'LinkedIn Jobs',
        site_url: 'https://www.linkedin.com/jobs/search/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
            'theatre',
        ],
        searchable: true,
        search_query_examples: [
            'https://www.linkedin.com/jobs/search?keywords=Front%20End%20Engineer&location=United%20States&trk=homepage-jobseeker_recent-search&redirect=false&position=1&pageNum=0',
            'https://www.linkedin.com/jobs/search?keywords=Video%20Editing&location=Denver%2C%20Colorado%2C%20United%20States&trk=guest_job_search_jobs-search-bar_search-submit&redirect=false&position=1&pageNum=0',
        ],
        search_url:
            'https://www.linkedin.com/jobs/search/?keywords=%q&location=United%20States',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Tech Ladies',
        site_url: 'https://www.hiretechladies.com/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
            'theatre',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.hiretechladies.com/',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Women For Hire',
        site_url: 'http://jobs.womenforhire.com/jobs/',
        iframe_able: false,
        tags: ['home', 'software', 'tech', 'women', 'female'],
        searchable: true,
        search_query_examples: [],
        search_url: 'http://jobs.womenforhire.com/jobs/',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: "Women's Job List",
        site_url: 'https://www.womensjoblist.com',
        iframe_able: true,
        tags: ['home', 'tech', 'women', 'female'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.womensjoblist.com',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Fairy God Boss',
        site_url: 'https://fairygodboss.com/jobs/filter',
        iframe_able: true,
        tags: ['home', 'tech', 'women', 'female'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://fairygodboss.com/search?term=%q',
    },
    {
        main_category: 'Women',
        type: 'job-board',
        site_name: 'Career Contessa',
        site_url: 'https://www.careercontessa.com/jobs/',
        iframe_able: true,
        tags: ['home', 'tech', 'women', 'female'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.careercontessa.com/jobs/',
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'Campus Pride',
        site_url: 'https://campuspride.jobs/',
        iframe_able: true,
        tags: ['campus', 'pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: true,
        search_query_examples: ['https://campuspride.jobs/jobs/?q=nurse'],
        search_url: 'https://campuspride.jobs/jobs/?q=%q',
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'LGBT Centers',
        site_url: 'https://www.lgbtcenters.org/Careers',
        iframe_able: true,
        tags: ['pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.lgbtcenters.org/Careers',
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'Pink Jobs',
        site_url: 'https://pink-jobs.com/jobs/',
        iframe_able: true,
        tags: ['pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://pink-jobs.com/jobs/',
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'All LGBT Jobs',
        site_url: 'https://alllgbtjobs.com/',
        iframe_able: true,
        tags: ['pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://alllgbtjobs.com/s/find-%q-jobs-in-usa',
    },
    {
        main_category: 'Pride',
        type: 'job-board',
        site_name: 'T Job Bank',
        site_url: 'http://tjobbank.com/',
        iframe_able: true,
        tags: ['pride', 'gay', 'lesbian', 'queer', 'trans'],
        searchable: false,
        search_query_examples: [],
        search_url: 'http://tjobbank.com/',
    },
    {
        main_category: 'Veterans',
        type: 'job-board',
        site_name: 'Veteran Jobs',
        site_url: 'http://vetjobs.com/',
        iframe_able: true,
        tags: ['military', 'veteran', 'army', 'navy', 'airforce', 'marines'],
        searchable: false,
        search_query_examples: [],
        search_url: 'http://vetjobs.com/',
    },
    {
        main_category: 'Veterans',
        type: 'job-board',
        site_name: 'Recruit Military',
        site_url: 'https://recruitmilitary.com/job-seekers',
        iframe_able: true,
        tags: ['military', 'veteran', 'army', 'navy', 'airforce', 'marines'],
        searchable: true,
        search_query_examples: [
            'https://success.recruitmilitary.com/jobs?utf8=%E2%9C%93&keywords=army&location=&commit=Search',
        ],
        search_url:
            'https://success.recruitmilitary.com/jobs?keywords=%q&location=',
    },
    {
        main_category: 'Veterans',
        type: 'job-board',
        site_name: 'Hire Heroes USA',
        site_url: 'https://jobs.hireheroesusa.org',
        iframe_able: false,
        tags: ['military', 'veteran', 'army', 'navy', 'airforce', 'marines'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://jobs.hireheroesusa.org/jobs/search?utf8=%E2%9C%93&q=%q&l=&lat=&long=&d=',
    },
    {
        main_category: 'Veterans',
        type: 'job-board',
        site_name: 'Military.com',
        site_url: 'https://www.military.com/veteran-jobs',
        iframe_able: false,
        tags: ['military', 'veteran', 'army', 'navy', 'airforce', 'marines'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://www.military.com/jobsearch/jobs?q=%q&date-posted=-1&page_index=1&onprem=1',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Black Jobs',
        site_url: 'https://www.blackjobs.com/?/cgi-bin/jobs/postJob.cgi',
        iframe_able: false,
        tags: [
            'african american',
            'black',
            'minority',
            'african',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [
            'https://www.blackjobs.com/jobs/search?utf8=%E2%9C%93&q=act&l=College+Station%2C+TX&lat=30.6032&long=-96.3136&d=',
        ],
        search_url:
            'https://www.blackjobs.com/jobs/search?utf8=%E2%9C%93&q=%q&l=&lat=&long=&d=',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Black Career Network',
        site_url: 'https://www.blackcareernetwork.com/',
        iframe_able: true,
        tags: [
            'african american',
            'black',
            'minority',
            'african',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [
            'https://www.blackcareernetwork.com/job-summaries?keywords=actions&location=Washington%2C+DC&organization=',
        ],
        search_url:
            'https://www.blackcareernetwork.com/job-summaries?keywords=%q',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'IM Diversity',
        site_url: 'https://jobs.imdiversity.com/cm/candidate/search_jobs',
        iframe_able: false,
        tags: [
            'african american',
            'black',
            'minority',
            'hispanic',
            'asian',
            'african',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [
            'https://jobs.imdiversity.com/candidate/job_search/quick/results?sort_field=post_date&keyword=action&sort_dir=desc',
        ],
        search_url:
            'https://jobs.imdiversity.com/candidate/job_search/quick/results?sort_field=post_date&keyword=%q&sort_dir=desc',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Hispanic Today',
        site_url: 'https://hispanic-today.com/career-search-engine/',
        iframe_able: true,
        tags: ['minority', 'hispanic', 'spanish', 'people of color', 'poc'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://hispanic-today.com/career-search-engine/',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'HLPA',
        site_url: 'https://jobs.hlpa.com/jobs/',
        iframe_able: true,
        tags: ['minority', 'hispanic', 'spanish', 'people of color', 'poc'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://jobs.hlpa.com/jobs/?listing_type%5Bequal%5D=Job&searchId=1567052602.9847&action=search&keywords%5Ball_words%5D=%q',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Diversity Jobs',
        site_url: 'https://diversityjobs.com/',
        iframe_able: true,
        tags: [
            'minority',
            'pride',
            'black',
            'african',
            'hispanic',
            'spanish',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [
            'https://diversityjobs.com/js/find-action-jobs-in-usa/age:356',
        ],
        search_url: 'https://diversityjobs.com/js/find-%q-jobs-in-usa',
    },
    {
        main_category: 'Minority',
        type: 'job-board',
        site_name: 'Diversity',
        site_url: 'https://www.diversity.com/list-jobs',
        iframe_able: true,
        tags: [
            'minority',
            'pride',
            'black',
            'african',
            'hispanic',
            'spanish',
            'people of color',
            'poc',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.diversity.com/list-jobs',
    },
    {
        main_category: 'Justice Involved',
        type: 'job-board',
        site_name: '70 Million Jobs',
        site_url: 'https://www.70millionjobs.com/',
        iframe_able: true,
        tags: [
            'criminal',
            'felony',
            'felon',
            'misdemeanor',
            'crime',
            'convict',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.70millionjobs.com/search',
    },
    {
        main_category: 'Justice Involved',
        type: 'job-board',
        site_name: 'Jail To Job',
        site_url: 'https://www.jailtojob.com/companies-hire-felons.html',
        iframe_able: true,
        tags: [
            'criminal',
            'felony',
            'felon',
            'misdemeanor',
            'crime',
            'convict',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.jailtojob.com/companies-hire-felons.html',
    },
    {
        main_category: 'Justice Involved',
        type: 'job-board',
        site_name: 'Hire Felons',
        site_url: 'https://www.hirefelons.org/best-jobs-for-felons/',
        iframe_able: true,
        tags: [
            'criminal',
            'felony',
            'felon',
            'misdemeanor',
            'crime',
            'convict',
        ],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.hirefelons.org/best-jobs-for-felons/',
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Recruit Disability',
        site_url: 'http://jobs.recruitdisability.org/jobs/search',
        iframe_able: true,
        tags: ['disabled', 'disability', 'impaired'],
        searchable: true,
        search_query_examples: [
            'http://jobs.recruitdisability.org/jobs/results/keyword/hearing/College+Station%2C+Texas?radius=25&SearchNetworks=US&networkView=national',
        ],
        search_url:
            'http://jobs.recruitdisability.org/jobs/results/title/%q?radius=25',
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Ability Links',
        site_url: 'https://abilitylinks.org/search/job',
        iframe_able: false,
        tags: ['disabled', 'disability', 'impaired'],
        searchable: true,
        search_query_examples: [
            'https://abilitylinks.org/search/job?search=distribution&field_job_region=All',
        ],
        search_url:
            'https://abilitylinks.org/search/job?search=%q&field_job_region=All',
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Getting Hired',
        site_url: 'https://www.gettinghired.com/',
        iframe_able: true,
        tags: ['disabled', 'disability', 'impaired', 'military'],
        searchable: true,
        search_query_examples: [
            'https://abilitylinks.org/search/job?search=distribution&field_job_region=All',
        ],
        search_url: 'https://www.gettinghired.com/?keyword=%q',
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Disability Job Exchange',
        site_url: 'https://www.disabilityjobexchange.com',
        iframe_able: true,
        tags: ['disabled', 'disability', 'impaired', 'military'],
        searchable: true,
        search_query_examples: [
            'https://abilitylinks.org/search/job?search=distribution&field_job_region=All',
        ],
        search_url: 'https://www.disabilityjobexchange.com/jobs/k-%q',
    },
    {
        main_category: 'Disabled',
        type: 'job-board',
        site_name: 'Disabled Person',
        site_url: 'https://www.disabledperson.com',
        iframe_able: false,
        tags: ['disabled', 'disability', 'impaired', 'military'],
        searchable: true,
        search_query_examples: [
            'https://abilitylinks.org/search/job?search=distribution&field_job_region=All',
        ],
        search_url:
            'https://www.disabledperson.com/jobs?utf8=%E2%9C%93&term=%q&location=',
    },
    {
        main_category: 'Cannabis',
        type: 'job-board',
        site_name: 'High Altitude Careers',
        site_url: 'https://highaltitudecareers.com/find-a-job/',
        iframe_able: false,
        tags: ['weed', 'marijuana', 'cannabis'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://highaltitudecareers.com/find-a-job/',
    },
    {
        main_category: 'Cannabis',
        type: 'job-board',
        site_name: 'Inweed',
        site_url: 'https://inweed.io',
        iframe_able: true,
        tags: ['weed', 'marijuana', 'cannabis'],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://inweed.io',
    },
    {
        main_category: 'Cannabis',
        type: 'job-board',
        site_name: 'Cannabis.net',
        site_url: 'https://jobs.cannabis.net/',
        iframe_able: false,
        tags: ['weed', 'marijuana', 'cannabis'],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://jobs.cannabis.net/candidate/job_search/quick/results?sort_field=post_date&keyword=%q&sort_dir=desc',
    },
    {
        main_category: 'Cannabis',
        type: 'job-board',
        site_name: '420 Careers',
        site_url: 'https://420careers.com/browse-jobs/',
        iframe_able: true,
        tags: ['weed', 'marijuana', 'cannabis'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://420careers.com/browse-jobs/?search_keywords=%q',
    },
    {
        main_category: 'Cannabis',
        type: 'job-board',
        site_name: 'Vangst',
        site_url: 'https://vangst.com/cannabis-jobseeker?page=0',
        iframe_able: true,
        tags: ['weed', 'marijuana', 'cannabis'],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://vangst.com/cannabis-jobseeker?page=0',
    },
    {
        main_category: 'Sales',
        type: 'job-board',
        site_name: 'Sales Gravy',
        site_url: 'https://www.salesgravy.com/JobBoard/',
        iframe_able: true,
        tags: [
            'sales',
            'account manager',
            'salesperson',
            'salesman',
            'saleswoman',
            'business development',
            'biz dev',
        ],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://www.salesgravy.com/JobBoard/index.php?action=search&what=%q&where=&p=1',
    },
    {
        main_category: 'Sales',
        type: 'job-board',
        site_name: 'Rainmakers',
        site_url: 'https://www.rainmakers.co',
        iframe_able: false,
        tags: [
            'sales',
            'account manager',
            'salesperson',
            'salesman',
            'saleswoman',
            'business development',
            'biz dev',
        ],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.rainmakers.co',
    },
    {
        main_category: 'Sales',
        type: 'job-board',
        site_name: 'Sales Jobs',
        site_url: 'https://www.salesjobs.com/',
        iframe_able: true,
        tags: [
            'sales',
            'account manager',
            'salesperson',
            'salesman',
            'saleswoman',
            'business development',
            'biz dev',
        ],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://www.salesjobs.com/findajob/index.asp?keywords=%q&location=&action=jobSearchResults',
    },
    {
        main_category: 'Sales',
        type: 'job-board',
        site_name: 'Sales Trax',
        site_url: 'https://www.salestrax.com/JSsearch.php',
        iframe_able: false,
        tags: [
            'sales',
            'account manager',
            'salesperson',
            'salesman',
            'saleswoman',
            'business development',
            'biz dev',
        ],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.salestrax.com/JSsearch.php',
    },
    {
        main_category: 'Sales',
        type: 'job-board',
        site_name: 'Sales Heads',
        site_url: 'https://www.salesheads.com/jobs/search',
        iframe_able: true,
        tags: [
            'sales',
            'account manager',
            'salesperson',
            'salesman',
            'saleswoman',
            'business development',
            'biz dev',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.salesheads.com/jobs/search?soid=1&k=%q&l=',
    },
    {
        main_category: 'Sales',
        type: 'job-board',
        site_name: 'Dado Match',
        site_url: 'https://www.dadomatch.com/job',
        iframe_able: true,
        tags: [
            'sales',
            'account manager',
            'salesperson',
            'salesman',
            'saleswoman',
            'business development',
            'biz dev',
        ],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.dadomatch.com/job',
    },
    {
        main_category: 'Executive',
        type: 'job-board',
        site_name: 'Ladders',
        site_url: 'https://www.theladders.com',
        iframe_able: true,
        tags: [
            'account manager',
            'business development',
            'biz dev',
            'executive',
            'c-suite',
        ],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.theladders.com',
    },
    {
        main_category: 'AR / VR',
        type: 'job-board',
        site_name: 'Jobs in XR',
        site_url: 'https://jobsinxr.com',
        iframe_able: true,
        tags: [
            'virtual reality',
            'augmented reality',
            'virtual',
            'augmented',
            '3D',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://jobsinxr.com/jobs/search?key=%q',
    },
    {
        main_category: 'AR / VR',
        type: 'job-board',
        site_name: 'VR Jobs Board',
        site_url: 'http://www.vrjobsboard.com/find-a-job/',
        iframe_able: true,
        tags: [
            'virtual reality',
            'augmented reality',
            'virtual',
            'augmented',
            '3D',
            'animation',
            'unreal',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'http://www.vrjobsboard.com/find-a-job/',
    },
    {
        main_category: 'AR / VR',
        type: 'job-board',
        site_name: 'VR Jobs Board 2',
        site_url: 'https://www.virtualrealityjobboard.com/',
        iframe_able: true,
        tags: [
            'virtual reality',
            'augmented reality',
            'virtual',
            'augmented',
            '3D',
            'animation',
            'unreal',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.virtualrealityjobboard.com/?query=%q',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'HigherEd Jobs',
        site_url: 'https://www.higheredjobs.com/search/',
        iframe_able: false,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://www.higheredjobs.com/search/advanced_action.cfm?Keyword=%q',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'Chronicle Vitae',
        site_url: 'https://chroniclevitae.com/job_search/new',
        iframe_able: false,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://chroniclevitae.com/job_search?utf8=%E2%9C%93&keyword_results_autosuggest=false&job_search%5Bkeywords%5D=%q&job_search%5Bposition_type%5D=&job_search%5Blocation%5D=&job_search%5Bstart_date%5D=&job_search%5Binstitution_type%5D=&job_search%5Bemployment_type%5D=&job_search%5Bdistance_from_zip%5D=10&job_search%5Bzip_code%5D=',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'Inside Higher Ed',
        site_url: 'https://careers.insidehighered.com/',
        iframe_able: false,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://careers.insidehighered.com/searchjobs/?Keywords=%q&radialtown=&LocationId=&RadialLocation=20',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'Academic Keys',
        site_url:
            'https://www.academickeys.com/all/choose_discipline.php?go=find_a_job',
        iframe_able: false,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: false,
        search_query_examples: [],
        search_url:
            'https://www.academickeys.com/all/choose_discipline.php?go=find_a_job',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'HigherEd 360',
        site_url: 'https://www.highered360.com/jobs/',
        iframe_able: false,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: false,
        search_query_examples: [],
        search_url: 'https://www.highered360.com/jobs/',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'Academic Positions',
        site_url: 'https://academicpositions.com/find-jobs/',
        iframe_able: true,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://academicpositions.com/find-jobs/all-in-all-by-all-in-all/%q/1',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'Academics.com',
        site_url: 'https://www.academics.com/',
        iframe_able: false,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://www.academics.com/jobsearch?q=%q',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'HREC',
        site_url: 'https://www.hercjobs.org/',
        iframe_able: true,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://main.hercjobs.org/jobs?keywords=%q&place=all&discipline=',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'The Uni Jobs',
        site_url:
            'https://www.timeshighereducation.com/unijobs/en-us/listings/',
        iframe_able: false,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: true,
        search_query_examples: [],
        search_url:
            'https://www.timeshighereducation.com/unijobs/en-us/listings/?Keywords=%q#browsing',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'Academic Careers',
        site_url: 'https://academiccareers.com/jobs/',
        iframe_able: true,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://academiccareers.com/jobs/?q=%q&l=',
    },
    {
        main_category: 'Academia',
        type: 'job-board',
        site_name: 'EU EDU Jobs',
        site_url: 'https://jobs.edu.eu/en/countries',
        iframe_able: true,
        tags: [
            'academia',
            'academic',
            'graduate',
            'post-grad',
            'higher ed',
            'research',
        ],
        searchable: true,
        search_query_examples: [],
        search_url: 'https://jobs.edu.eu/en',
    },
    {
        main_category: 'Best Places To Work',
        type: 'job-board',
        site_name: '2019 Best Places To Work',
        site_url:
            'https://www.glassdoor.com/Award/Best-Places-to-Work-LST_KQ0,19.htm',
        iframe_able: false,
        tags: [
            'best places to work',
            'top places',
            'quality places',
            'quality',
            'best',
        ],
        searchable: false,
        search_query_examples: [],
        search_url:
            'https://www.glassdoor.com/Award/Best-Places-to-Work-LST_KQ0,19.htm',
    },
    {
        main_category: 'Best Places To Work',
        type: 'job-board',
        site_name: '2018 Best Places To Work',
        site_url:
            'http://money.com/money/5047491/the-100-best-places-to-work-in-2018/',
        iframe_able: false,
        tags: [
            'best places to work',
            'top places',
            'quality places',
            'quality',
            'best',
        ],
        searchable: false,
        search_query_examples: [],
        search_url:
            'http://money.com/money/5047491/the-100-best-places-to-work-in-2018/',
    },
    {
        main_category: 'Best Places To Work',
        type: 'job-board',
        site_name: 'Built In Austin',
        site_url:
            'https://www.builtinaustin.com/companies/best-places-to-work-austin',
        iframe_able: false,
        tags: [
            'best places to work',
            'top places',
            'quality places',
            'quality',
            'best',
        ],
        searchable: false,
        search_query_examples: [],
        search_url:
            'https://www.builtinaustin.com/companies/best-places-to-work-austin',
    },
    {
        main_category: 'Best Places To Work',
        type: 'job-board',
        site_name: 'Built In Colorado',
        site_url:
            'https://www.builtincolorado.com/companies/best-places-to-work-colorado-2019',
        iframe_able: false,
        tags: [
            'best places to work',
            'top places',
            'quality places',
            'quality',
            'best',
        ],
        searchable: false,
        search_query_examples: [],
        search_url:
            'https://www.builtincolorado.com/companies/best-places-to-work-colorado-2019',
    },
    {
        main_category: 'Best Places To Work',
        type: 'job-board',
        site_name: 'Top Rated 2019',
        site_url:
            'https://www.indeed.com/Top-Rated-Workplaces/2019-US-The-Top-50',
        iframe_able: false,
        tags: [
            'best places to work',
            'top places',
            'quality places',
            'quality',
            'best',
        ],
        searchable: false,
        search_query_examples: [],
        search_url:
            'https://www.indeed.com/Top-Rated-Workplaces/2019-US-The-Top-50',
    },
];

// Processing
addSlugsToSites(sitesMaster); // run this in-place to save memory

// Exports
export const sites = sitesMaster;
export const sitesBySlug = groupBySlugs(sites);
