export const sites = [
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remote Ok',
        site_url: 'https://remoteok.io/',
        iframe_able: true,
        tags: ['remote', 'development', 'coding'],
        searchable: true,
        search_query_examples: [
            'https://remoteok.io/remote-video-editing-jobs',
            'https://remoteok.io/remote-customer-support+css-jobs',
        ],
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'CodePen Jobs',
        site_url: 'https://codepen.io/jobs/',
        iframe_able: true,
        tags: ['software', 'remote'],
        searchable: true,
        search_query_examples: ['https://codepen.io/jobs.json'],
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'GitHub Jobs',
        site_url: 'https://jobs.github.com/positions/',
        iframe_able: false,
        tags: ['software', 'remote'],
        searchable: true,
        search_query_examples: [
            'https://jobs.github.com/positions?utf8=%E2%9C%93&description=React&location=',
            'https://jobs.github.com/positions?utf8=%E2%9C%93&description=Java&location=San+Fransisco',
        ],
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'Monday.vc',
        site_url: 'https://www.monday.vc/jobs/',
        iframe_able: true,
        tags: ['software', 'remote', 'startups', 'venture backed'],
        searchable: true,
        search_query_examples: [
            'https://www.monday.vc/jobs?q=Dev%20Ops',
            'https://www.monday.vc/jobs?q=Content%20Creator',
        ],
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'TechStars',
        site_url: 'https://jobs.techstars.com/',
        iframe_able: true,
        tags: ['software', 'remote', 'startups', 'venture backed'],
        searchable: true,
        search_query_examples: [
            'https://jobs.techstars.com/?q=Intern',
            'https://jobs.techstars.com/?t=1197&j=1064993781&l=90',
        ],
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'YC Engineering Jobs',
        site_url: 'https://www.workatastartup.com/',
        iframe_able: false,
        tags: [
            'software',
            'remote',
            'startups',
            'venture backed',
            'yc',
            'y combinator',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'YC Non-Engineering Jobs',
        site_url: 'https://ycombinator.monday.vc/',
        iframe_able: false,
        tags: ['remote', 'startups', 'venture backed', 'yc', 'y combinator'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Career Builder',
        site_url: 'https://www.careerbuilder.com/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [
            'https://www.careerbuilder.com/jobs?utf8=%E2%9C%93&keywords=Marketing&location=Austin+Tx',
            'https://www.careerbuilder.com/jobs?utf8=%E2%9C%93&keywords=React&location=Denver%2C+CO',
        ],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Indeed',
        site_url: 'https://www.indeed.com/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [
            'https://www.indeed.com/q-full-stack-developer-l-College-Station,-TX-jobs.html',
            'https://www.indeed.com/jobs?q=theater+teacher&l=Oregon',
        ],
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Twitch',
        site_url: 'https://boards.greenhouse.io/twitch',
        iframe_able: true,
        tags: ['tech', 'startups', 'gaming', 'video', 'software'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Glassdoor',
        site_url: 'https://www.glassdoor.com/index.htm/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [
            'https://www.glassdoor.com/Job/react-native-jobs-SRCH_KO0,12.htm',
            'https://www.glassdoor.com/Job/seattle-full-stack-web-dev-jobs-SRCH_IL.0,7_IC1150505_KE8,26.htm',
        ],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'FlexJobs',
        site_url: 'https://www.flexjobs.com/jobs/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [
            'https://www.flexjobs.com/jobs/graphic-design',
            'https://www.flexjobs.com/search?search=Full+Stack+Web+Developer&location=Denver%2C+CO',
        ],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'We Work Remotely',
        site_url: 'https://weworkremotely.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [
            'https://weworkremotely.com/remote-jobs/search?utf8=%E2%9C%93&term=React',
            'https://weworkremotely.com/remote-jobs/search?utf8=%E2%9C%93&term=React+Native',
        ],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remote.co',
        site_url: 'https://remote.co/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: true,
        search_query_examples: [
            'https://remote.co/remote-jobs/search/?search_keywords=customer+service',
            'https://remote.co/remote-jobs/search/?search_keywords=Tech+Sales',
        ],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Virtual Vocation',
        site_url: 'https://www.virtualvocations.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Pangian',
        site_url: 'https://pangian.com/job-travel-remote/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Remotive',
        site_url: 'https://remotive.io/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Working Nomads',
        site_url: 'https://www.workingnomads.co/jobs',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Jobspresso',
        site_url: 'https://jobspresso.co/remote-work/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Eurpoe Remote',
        site_url: 'https://europeremotely.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Outsourcely',
        site_url: 'https://www.outsourcely.com/remote-workers',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Power To Fly',
        site_url: 'https://powertofly.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Landing Jobs',
        site_url: 'https://landing.jobs/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Remote',
        type: 'job-board',
        site_name: 'Authentic Jobs',
        site_url: 'https://authenticjobs.com/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'job-board',
        site_name: 'Dribbble',
        site_url: 'https://dribbble.com/jobs',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: '99designs',
        site_url: 'https://99designs.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'job-board',
        site_name: 'Behance',
        site_url: 'https://www.behance.net/joblist',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: 'DesignCrowd',
        site_url: 'https://jobs.designcrowd.com/jobs/',
        iframe_able: true,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: 'Envato Studio',
        site_url: 'https://studio.envato.com/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Design',
        type: 'marketplace',
        site_name: 'Working Not Working',
        site_url: 'https://workingnotworking.com/search/jobs/',
        iframe_able: false,
        tags: ['remote', 'part-time', 'freelance', 'design', 'graphics'],
        searchable: true,
        search_query_examples: [
            'https://workingnotworking.com/search/everywhere/jobs/ux-ia-designer',
            'https://workingnotworking.com/search/new-york-ny-usa',
        ],
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'Stack Overflow',
        site_url: 'https://stackoverflow.com/jobs/',
        iframe_able: false,
        tags: [
            'software',
            'part-time',
            'freelance',
            'software engineering',
            'remote',
        ],
        searchable: true,
        search_query_examples: [''],
    },
    {
        main_category: 'Software',
        type: 'job-board',
        site_name: 'Smashing Jobs',
        site_url: 'https://jobs.smashingmagazine.com/jobs/',
        iframe_able: false,
        tags: [
            'software',
            'part-time',
            'freelance',
            'design',
            'remote',
            'developers',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'The Muse',
        site_url: 'https://www.themuse.com/jobs/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate'],
        searchable: true,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Idealist',
        site_url: 'https://www.idealist.org/en/?searchMode=true&type=JOB/',
        iframe_able: false,
        tags: ['career', 'all jobs', 'corporate', 'internships', 'startups'],
        searchable: true,
        search_query_examples: [''],
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Crytocurrency Jobs',
        site_url: 'https://cryptocurrencyjobs.co/',
        iframe_able: true,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'CryptoJobs',
        site_url: 'https://crypto.jobs',
        iframe_able: false,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Crypto Jobs List',
        site_url: 'https://cryptojobslist.com/',
        iframe_able: true,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Crypto',
        type: 'job-board',
        site_name: 'Crypto Careers',
        site_url: 'https://www.crypto-careers.com/',
        iframe_able: false,
        tags: ['software', 'startups', 'crypto', 'blockchain'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'F6S',
        site_url: 'https://www.f6s.com/jobs?sort=newest/',
        iframe_able: false,
        tags: ['software', 'startups', 'operations', ''],
        searchable: true,
        search_query_examples: [''],
    },
    {
        main_category: 'Startups',
        type: 'job-board',
        site_name: 'Growth Hackers',
        site_url: 'https://growthhackers.com/jobs/',
        iframe_able: false,
        tags: ['software', 'startups', 'operations', 'growth hacker', 'growth'],
        searchable: true,
        search_query_examples: [''],
    },
    {
        main_category: 'Software',
        type: 'match-service',
        site_name: 'Gun.io',
        site_url: 'https://www.gun.io/',
        iframe_able: true,
        tags: ['software'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'US.jobs',
        site_url: 'https://us.jobs/search/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'temporary', 'minority'],
        searchable: true,
        search_query_examples: [''],
    },
    {
        main_category: 'Software',
        type: 'company',
        site_name: 'GitLab',
        site_url: 'https://boards.greenhouse.io/gitlab',
        iframe_able: true,
        tags: ['software'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Software',
        type: 'company',
        site_name: 'WP Hired',
        site_url: 'https://www.wphired.com/jobs/',
        iframe_able: false,
        tags: ['software', 'sales', 'customer service'],
        searchable: true,
        search_query_examples: [
            'https://www.wphired.com/jobs/?search_keywords=sales&search_region=0&search_categories%5B%5D=&submit=Search&filter_job_type%5B%5D=',
        ],
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Airbnb',
        site_url: 'https://careers.airbnb.com/',
        iframe_able: false,
        tags: ['photography', 'sales', 'customer service', 'software'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Amazon',
        site_url: 'https://www.amazon.jobs/',
        iframe_able: false,
        tags: ['university', 'sales', 'customer service', 'software', 'entry'],
        searchable: true,
        search_query_examples: [
            'https://www.amazon.jobs/en-gb/search?base_query=Utah&loc_query=',
        ],
    },
    {
        main_category: 'Tech Companies',
        type: 'company',
        site_name: 'Microsoft',
        site_url: 'https://careers.microsoft.com/',
        iframe_able: false,
        tags: ['university', 'sales', 'customer service', 'software', 'entry'],
        searchable: true,
        search_query_examples: [
            'https://careers.microsoft.com/us/en/search-results?keywords=Sales',
        ],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Salesforce Job Board',
        site_url: 'https://appexchange.salesforce.com/jobs',
        iframe_able: true,
        tags: ['software', 'sales', 'customer service'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Health Care',
        type: 'job-board',
        site_name: 'Health Ecareers',
        site_url: 'https://www.healthecareers.com/search-jobs/',
        iframe_able: true,
        tags: ['health care', 'medical', 'nurse', 'internship', 'doctors'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Health Care',
        type: 'job-board',
        site_name: 'Gas Work',
        site_url: 'https://www.gaswork.com/',
        iframe_able: true,
        tags: ['medical gas', 'medical', 'gas'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Monster.com',
        site_url: 'https://monster.com/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'corporate'],
        searchable: true,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Simply Hired',
        site_url: 'https://www.simplyhired.com/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'corporate'],
        searchable: true,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'Zip Recruiter',
        site_url: 'https://ziprecruiter.com/Jobs/Search/',
        iframe_able: false,
        tags: ['all jobs', 'career', 'corporate'],
        searchable: true,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Uber',
        site_url: 'https://www.uber.com/drive',
        iframe_able: false,
        tags: ['gig', 'driving', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Lyft',
        site_url: 'https://www.lyft.com/drive-with-lyft',
        iframe_able: true,
        tags: ['gig', 'driving', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Uber Eats',
        site_url: 'https://www.uber.com/drive/delivery/',
        iframe_able: false,
        tags: ['gig', 'driving', 'food delivery', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Grubhub',
        site_url: 'https://driver.grubhub.com/',
        iframe_able: true,
        tags: ['gig', 'driving', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'DoorDash',
        site_url: 'https://www.doordash.com/dasher/signup/',
        iframe_able: false,
        tags: ['gig', 'driving', 'food delivery', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'PostMates',
        site_url: 'https://fleet.postmates.com/',
        iframe_able: true,
        tags: ['gig', 'driving', 'food delivery', 'part-time'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'SimplePuppy',
        site_url: 'https://simplepuppy.com/',
        iframe_able: true,
        tags: ['gig', 'pets', 'pet sitting', 'part-time', 'pet grooming'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Gig Economy',
        type: 'company',
        site_name: 'Wag!',
        site_url: 'https://wagwalking.com/dog-walker',
        iframe_able: false,
        tags: ['gig', 'pets', 'pet sitting', 'part-time', 'pet grooming'],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Journalism Jobs',
        site_url: 'https://www.journalismjobs.com/job-listings',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Contena',
        site_url: 'https://www.contena.co/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'FWJ',
        site_url:
            'https://www.freelancewritinggigs.com/freelance-writing-job-ads/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Freelance Writing',
        site_url: 'https://www.freelancewriting.com/jobs/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'All Freelance Writing',
        site_url: 'https://allfreelancewriting.com/freelance-writing-jobs/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'Media Bistro',
        site_url: 'https://www.mediabistro.com/jobs/openings/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'company',
        site_name: 'Due.com',
        site_url: 'https://due.com/guest-post-on-due/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board',
        site_name: 'PubLoft',
        site_url: 'https://publoft.com/writers',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Writing',
        type: 'job-board, request driven really',
        site_name: 'Contently',
        site_url: 'https://contently.net/about-us/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'writing',
            'ghost writing',
            'editing',
            'author',
            'journalism',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Production Hub',
        site_url: 'https://www.productionhub.com/jobs',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Stage 32',
        site_url: 'https://www.stage32.com/find-jobs',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Assemble',
        site_url: 'https://www.assemble.tv/talent',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Video',
        type: 'job-board',
        site_name: 'Mandy',
        site_url: 'https://www.mandy.com/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
            'theatre',
        ],
        searchable: false,
        search_query_examples: [''],
    },
    {
        main_category: 'Job Boards',
        type: 'job-board',
        site_name: 'LinkedIn Jobs',
        site_url: 'https://www.linkedin.com/jobs/search/',
        iframe_able: false,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
            'theatre',
        ],
        searchable: true,
        search_query_examples: [
            'https://www.linkedin.com/jobs/search?keywords=Front%20End%20Engineer&location=United%20States&trk=homepage-jobseeker_recent-search&redirect=false&position=1&pageNum=0',
            'https://www.linkedin.com/jobs/search?keywords=Video%20Editing&location=Denver%2C%20Colorado%2C%20United%20States&trk=guest_job_search_jobs-search-bar_search-submit&redirect=false&position=1&pageNum=0',
        ],
    },
    {
        main_category: 'Woman Focused',
        type: 'job-board',
        site_name: 'Tech Ladies',
        site_url: 'https://www.hiretechladies.com/',
        iframe_able: true,
        tags: [
            'gig',
            'freelance',
            'video',
            'editing',
            'directing',
            'motion',
            'film',
            'theatre',
        ],
        searchable: true,
        search_query_examples: [
            'https://www.linkedin.com/jobs/search?keywords=Front%20End%20Engineer&location=United%20States&trk=homepage-jobseeker_recent-search&redirect=false&position=1&pageNum=0',
            'https://www.linkedin.com/jobs/search?keywords=Video%20Editing&location=Denver%2C%20Colorado%2C%20United%20States&trk=guest_job_search_jobs-search-bar_search-submit&redirect=false&position=1&pageNum=0',
        ],
    },
];
